#ifndef __FLAG_DATA__
#define __FLAG_DATA__

// clang-format off
{0x228, 4, "Igor/Sue not in Eggs", false},
{0x228, 5, "POWER-UP - Life Capsule in Eggs (1)", false},
{0x228, 6, "POWER-UP - Life Capsule in Eggs (2)", false},
{0x228, 7, "Igor defeated (opens doors from Eggs to EggX, Eggs2 to EggX2)", false},
{0x229, 1, "Opens door from Eggs to Side Room", false},
{0x229, 2, "Teleport from Eggs/Eggs2 to Pens2 instead of Pens1 (for Pens cutscene)", false},
{0x22B, 0, "Sue not in EggX", false},
{0x22D, 4, "ITEM - ID Card", false},
{0x22E, 7, "[UNUSED? - dummied treasure chest in Pens1? the chest triggers a nonexistant event]", false},
{0x22F, 1, "Prevents Egg Chamber teleportation", false},
{0x22F, 2, "Jack in Pens1, King in Mimi (after Eggs, before King leaves to resure Toroko)", false},
{0x22F, 3, "Shows first Sue in cage cutscene after leaving Pens1", false},
{0x22F, 4, "Kazuma, Booster, Sue, King in Pens1", false},
{0x22F, 5, "Kazuma/Booster arrival cutscene (set during second Sue in cage cutscene)", false},
{0x22F, 6, "Teleporter access to Sand Zone", false},
{0x22F, 7, "Teleport to Eggs2 instead of Eggs (after drowning cutscene)", false},
{0x230, 0, "Triggers Booster v2.0 dialogue", false},
{0x230, 1, "Booster survived", false},
{0x230, 2, "ITEM - Booster v2.0", false},
{0x235, 0, "POWER-UP - Missiles in EggR", false},
{0x235, 1, "WEAPON - Missile Launcher (enables hidden Missile ammo entities)", false},
{0x235, 2, "WEAPON - Super Missile", false},
{0x236, 2, "ITEM - Santa's Key", false},
{0x236, 3, "Talked to Santa about key", false},
{0x236, 4, "Gave Santa's Key to Santa", false},
{0x236, 5, "Fireplace grate is gone", false},
{0x236, 6, "Opens door from Weed to Malco", false},
{0x236, 7, "ITEM - Rusty Key", false},
{0x237, 0, "Tried Rusty Key on door to Shelt (dialogue change if you try it again)", false},
{0x237, 1, "[Deactivates teleporter in Weed - not sure when/why]", false},
{0x237, 2, "POWER-UP - Missiles in Weed", false},
{0x237, 3, "Shows second Sue in cage cutscene after leaving Weed (set after Kazuma/Booster take scooter) ", false},
{0x237, 4, "POWER-UP - Life Capsule in Weed", false},
{0x237, 5, "ITEM - Gum Key", false},
{0x237, 6, "Opens door from Weed to Frog", false},
{0x237, 7, "Told Kazuma that Rusty Key doesn't work on Door to Shelt (dialogue change if you talk to him again)", false},
{0x238, 0, "Have visited Weed (dialogue change with caged Sue and King next to her)", false},
{0x238, 1, "Scooter not at shelter", false},
{0x238, 2, "Scooter crashed", false},
{0x238, 3, "Scooter wreckage is smoking (stops once you teleport or enter Santa's house)", false},
{0x238, 4, "Talked to Cthulhu 1 in Weed once (dialogue change)", false},
{0x23A, 0, "[set with 0241, Santa dialogue jump is after 0241's, jump target doesn't exist]", false},
{0x23A, 1, "WEAPON - Fireball, (dialogue changes regarding Chaco's fireplace)", false},
{0x23A, 2, "Got Charcoal", false},
{0x23A, 3, "Santa kidnapped", false},
{0x23C, 5, "Learned about Jellyfish Juice (enables enemies)", false},
{0x23C, 6, "Chaco kidnapped", false},
{0x23C, 7, "Can get Lipstick (use bed right after Chaco first mentions Jellyfish Juice)", false},
{0x23D, 6, "POWER-UP - Life Capsule in Sand (1)", false},
{0x23D, 7, "POWER-UP - Life Capsule 2 in Sand (2)", false},
{0x23E, 0, "Defeated Omega (Sunstones move when you reach them)", false},
{0x23E, 1, "Sunstones moved", false},
{0x23E, 2, "Currently have a Puppy on your back", false},
{0x23E, 3, "ITEM - Kakeru (puppy)", false},
{0x23E, 4, "ITEM - Nene (puppy)", false},
{0x23E, 5, "[Shinobu leaves Sand? I don't understand how this is set]", false},
{0x23E, 6, "Opens door from Sand to Gard", false},
{0x23E, 7, "ITEM - Mick (puppy)", false},
{0x23F, 0, "Go to Jenka2 instead of Jenka1 (Balrog stole storehouse key)", false},
{0x23F, 1, "Curly not in Sand (saw you at entrance and ran away)", false},
{0x241, 5, "Opens door from Cave to Mimi", false},
{0x241, 6, "Entered Mimi once (disables falling on King cutscene)", false},
{0x241, 7, "More enemies in Cave", false},
{0x242, 0, "ITEM - Life Capsule in Cave", false},
{0x244, 0, "Toroko, King moved from platform (after falling on King)", false},
{0x244, 1, "King on left side of platform (before getting locket)", false},
{0x244, 2, "ITEM - Map System", false},
{0x244, 3, "Talked to King on platform once", false},
{0x244, 4, "Opens door from Mimi to Pens1", false},
{0x244, 5, "Teleporter access to Grasstown", false},
{0x244, 6, "King near door from Mimi to Pool", false},
{0x244, 7, "Jack stops guarding door to Cemet", false},
{0x245, 1, "Sue caged in Mimi", false},
{0x246, 4, "Mahin kidnapped (after drowning cutscene)", false},
{0x246, 5, "Changes music in Mimiga areas (after drowning cutscene)", false},
{0x249, 0, "Toroko kidnapped", false},
{0x249, 1, "Currently fighting Balrog", false},
{0x249, 2, "Locks door from Barr to Mimi", false},
{0x24A, 2, "ITEM - Silver Locket", false},
{0x24A, 3, "Toroko not in Pool", false},
{0x24A, 4, "Kanpachi kidnapped", false},
{0x24C, 6, "ITEM - Arthur's Key", false},
{0x24C, 7, "ITEM - Little Man", false},
{0x24F, 2, "ITEM - Beast Fang (can't get it)", false},
{0x24F, 3, "Sandaime kidnapped", false},
{0x24F, 4, "POWER-UP - Life Capsule in Plant", false},
{0x251, 6, "Saw first Kazuma on computer cutscene", false},
{0x251, 7, "Have saved at least once (loads saved game on Retry)", false},
{0x253, 0, "King in Comu", false},
{0x253, 1, "[set when first entering Pens1, but has no effect?]", false},
{0x253, 2, "WEAPON - Bubbler", false},
{0x253, 3, "Jack in Comu after leaving Cemet door", false},
{0x253, 4, "Jack in Comu after Kazuma/Booster arrive", false},
{0x256, 6, "Shield lowered in Eggs (used ID Card)", false},
{0x258, 0, "Currently fighting Balrog 2 (locks door from Malco to Weed)", false},
{0x258, 1, "Fans activated", false},
{0x258, 2, "Defeated Balrog 2 (can pull Malco out of ground)", false},
{0x258, 3, "Malco is not inactive or in ground", false},
{0x258, 4, "Malco says he can make a bomb", false},
{0x258, 5, "Malco is standing", false},
{0x258, 6, "ITEM - Explosive", false},
{0x25A, 4, "Currently fighting Balfrog (locks door from Frog to Weed)", false},
{0x25A, 5, "ITEM - Gum Base", false},
{0x25D, 0, "Opens door from Weed to Shelt", false},
{0x25D, 1, "Kazuma is not at the computer", false},
{0x25D, 2, "Kazuma is standing", false},
{0x25D, 3, "Kazuma/Booster in Weed (before scooter)", false},
{0x25D, 4, "Teleporter in Shelt is active", false},
{0x25D, 5, "Save Point and Health Refill appear in Shelt", false},
{0x25F, 4, "POWER-UP - Life Capsule in WeedD", false},
{0x260, 6, "POWER-UP - Missiles in WeedB (fought Rabil)", false},
{0x262, 0, "[set when Curly fight starts]", false},
{0x262, 1, "Currently fighting Curly (locks doors from Curly to Sand/CurlyS)", false},
{0x262, 2, "Told Curly you won't kill the Mimigas", false},
{0x262, 3, "WEAPON - Machine Gun", false},
{0x262, 4, "Can get Hajime (after Jenka asks you to get the puppies)", false},
{0x262, 5, "Curly and Mimiga children not in Curly (sand zone residence)   I don't understand how the Curly fight sets this…", false},
{0x264, 4, "ITEM - Hajime", false},
{0x264, 5, "ITEM - Curly's Underwear", false},
{0x265, 6, "Gave 1st Puppy to Jenka (note: says \"Arf!\"", false},
{0x265, 7, "Gave 2nd Puppy to Jenka (note: says \"Arf arf!\"", false},
{0x266, 0, "Gave 3rd Puppy to Jenka (note: says \"Arf arf arf!\"", false},
{0x266, 1, "Gave 4th Puppy to Jenka (note: says \"Booop.\"", false},
{0x266, 2, "Gave 5th Puppy to Jenka (note: says \"Five!\", but you don't get a chance to talk to it)", false},
{0x266, 3, "Balrog stole storehouse key", false},
{0x266, 4, "Jenka stood up after Balrog's attack", false},
{0x268, 2, "ITEM - Shinobu", false},
{0x269, 4, "Saw Toroko red flowers cutscene", false},
{0x269, 5, "Currently fighting Frenzied Toroko (locks door from Gard to Sand)", false},
{0x269, 6, "King died", false},
{0x269, 7, "Frenzied Toroko defeated (can talk to King)", false},
{0x26A, 0, "Door leads to SandE (for Misery teleport cutscene)", false},
{0x26C, 0, "[something with Quote falling into the room?]", false},
{0x26C, 1, "Opens door from MazeI to MazeH", false},
{0x26C, 2, "POWER-UP - Life Capsule in MazeI", false},
{0x271, 0, "[Monster X fight triggered?]", false},
{0x271, 1, "Opens door from MazeW to MazeD", false},
{0x273, 4, "ITEM - Clinic Key", false},
{0x273, 5, "Talked to Curly in MazeO once", false},
{0x273, 6, "Gave Cure All to Gero", false},
{0x273, 7, "Curly will be cured", false},
{0x274, 0, "Curly not in MazeW", false},
{0x274, 1, "ITEM - Arms Barrier", false},
{0x274, 6, "Currently fighting Pooh Black (locks door from MazeD to MazeW)", false},
{0x274, 7, "ITEM - Cure All", false},
{0x276, 0, "Teleporter in MazeM active", false},
{0x276, 1, "Bought something from Chaba (Turbocharge, Snake, or Whimsical Star)", false},
{0x276, 2, "EQUIP - Whimsical Star", false},
{0x278, 4, "Saw Booster fall in MazeB", false},
{0x278, 5, "Booster not in MazeB", false},
{0x278, 6, "EQUIP - Booster v0.8", false},
{0x278, 7, "EQUIP - Booster v2.0", false},
{0x279, 0, "Teleporter in MazeB active", false},
{0x27B, 0, "Curly not in MazeO", false},
{0x27B, 1, "Curly ready to lift boulder", false},
{0x27B, 2, "Balrog in MazeS", false},
{0x27B, 3, "Currently fighting Balrog 3 (locks door from MazeS to MazeB)", false},
{0x27B, 4, "Opens door from MazeS to MazeM (boulder moved)", false},
{0x27B, 5, "Balrog 3 defeated (Super Missile chest appears)", false},
{0x27B, 6, "WEAPON - Super Missile", false},
{0x27D, 4, "Passageway in MazeM permanently open (from entering Drain once)", false},
{0x27D, 5, "Curly in MazeM", false},
{0x27D, 6, "Used computer to open passageway in MazeM", false},
{0x27D, 7, "Locks door from MazeM to Drain (after drowning cutscene)", false},
{0x280, 0, "Locks door from Drain to MazeM (after drowning cutscene)", false},
{0x280, 1, "Opens grate from MazeM to River (after drowning cutscene)", false},
{0x282, 4, "Curly is next to first shutter", false},
{0x282, 5, "Opens shutters", false},
{0x282, 6, "Shutter 4 stuck, Curly is next to shutter 4", false},
{0x282, 7, "Shutter 4 fixed", false},
{0x283, 0, "Lowered lift in Almond", false},
{0x283, 1, "Opens big shutter", false},
{0x283, 2, "Curly is next to big shutter", false},
{0x283, 3, "Curly is next to broken robot", false},
{0x283, 4, "Currently fighting Core (can't get Tow Rope)", false},
{0x283, 5, "Curly drowning in Almond (before picking her up with Tow Rope)", false},
{0x283, 6, "[lots of effects, set after drowning cutscene]", false},
{0x283, 7, "Closes big shutter", false},
{0x284, 0, "[water level rose?]", false},
{0x284, 2, "ITEM - Tow Rope (also set when getting Booster v0.8)", false},
{0x284, 3, "Brought Curly out of Almond (computer in Pixel mentions notebook)", false},
{0x284, 4, "Currently have Curly (unconscious) on your back", false},
{0x284, 5, "Core defeated (Curly dialogue change)", false},
{0x284, 6, "[set after drowning cutscene, but has no effect?]", false},
{0x284, 7, "Locks door from Almond to Drain (after getting Tow Rope, before drowning cutscene)", false},
{0x286, 2, "River leads to Pool instead of Stream (but you can't get back to River anyway)", false},
{0x286, 3, "Curly dead (after message shown in River)", false},
{0x28A, 0, "POWER-UP - Missiles in Eggs2", false},
{0x28F, 0, "POWER-UP - Missiles in EggR2 (makes Save Point appear)", false},
{0x28F, 1, "Currently fighting Sisters (locks doors from EggR2 to Eggs2)", false},
{0x28F, 3, "Sisters defeated (small spikes gone from EggR2)", false},
{0x291, 4, "Opens door from EggX2 to Oside", false},
{0x291, 5, "Kazuma entered EggX2", false},
{0x294, 0, "Told Kazuma you'd escape with him (triggers bad ending if you talk to him in Oside)", false},
{0x294, 1, "Kazuma and Sky Dragon not in Oside", false},
{0x299, 0, "Scared Itoh", false},
{0x299, 1, "Talked to Itoh once", false},
{0x299, 2, "Talked to Itoh twice", false},
{0x299, 3, "ITEM - Controller", false},
{0x299, 4, "Itoh not in Itoh (the storehouse)", false},
{0x29B, 4, "EQUIP - Mimiga Mask (note: there's a jump in the credits, but it doesn't change anything - was he going to have different illustrations?)", false},
{0x29B, 5, "Kanpachi in Cent with bucket, sparkle not in Cent (he caught it)", false},
{0x29B, 6, "ITEM - Teleporter Room Key", false},
{0x29B, 7, "Opens door from Cent to CentW", false},
{0x29C, 0, "Know Momorin's password (can enter door from Cent to Momo)", false},
{0x29C, 1, "Red Flowers growing in Cent", false},
{0x29C, 2, "Red Flowers blooming in Cent", false},
{0x29C, 3, "Leftmost (working) sprinkler not in Cent", false},
{0x29C, 4, "Broken Sprinkler in Cent", false},
{0x29C, 5, "Can get Broken Sprinkler (after Shovel Brigade guy tells you to replace it)", false},
{0x29C, 6, "Rocket is finished (opens door from Cent to Priso1/Priso2)", false},
{0x29C, 7, "Itoh in Cent", false},
{0x29D, 0, "Momorin in Cent", false},
{0x29D, 1, "Shovel Brigade and other Mimigas taken away", false},
{0x29D, 2, "Momorin took Mimiga Mask and gave back Booster", false},
{0x29D, 3, "Can get Teleporter Room Key (Kanpachi told you he caught something)", false},
{0x29D, 4, "Red Flowers, Sprinklers not in Cent (petals are left)", false},
{0x29D, 5, "Talked to Shovel Brigade (the talkative one) without Mimiga Mask once", false},
{0x29D, 6, "[set after meeting Itoh, cleared after long sleep in Momo]", false},
{0x29D, 7, "[set after long sleep in Momo - Drolls gone, Puppy appears, more? rocket?]", false},
{0x29E, 0, "POWER-UP - Life Capsule in Cent (2)", false},
{0x29E, 1, "Talked to Curly in Cent once", false},
{0x29E, 2, "Curly survived after Stream (can get Nikumaru Counter)", false},
{0x29E, 3, "POWER-UP - Life Capsule in Cent (1)", false},
{0x29E, 4, "Talked to Cthulhu in Cent once", false},
{0x29E, 5, "Restored Curly's memory", false},
{0x29E, 6, "ITEM - Iron Bond", false},
{0x2A3, 0, "Talked to Mahin in Jail1 once", false},
{0x2A3, 1, "Talked to Mahin in Jail1 twice", false},
{0x2A3, 2, "Sue and Jack not in Jail1", false},
{0x2A5, 4, "Talked to Momorin once", false},
{0x2A5, 5, "ITEM - Mimiga Mask", false},
{0x2A5, 6, "Know to talk to Itoh for Momorin (note: sprinklers in Cent use this for dialogue, but should probably use 1121)", false},
{0x2A5, 7, "Can use bed in Momo (long sleep)", false},
{0x2A6, 1, "Momorin not in Momo", false},
{0x2A6, 2, "Gave Booster to Momorin", false},
{0x2A6, 3, "Gave Sprinkler to Momorin", false},
{0x2A8, 0, "Kanpachi not in Lounge", false},
{0x2A8, 1, "ITEM - Sprinkler", false},
{0x2AA, 4, "Was captured by Droll (doesn't appear again)", false},
{0x2AA, 5, "Used Teleporter in CentW once (redundant with 1140 set)", false},
{0x2B0, 6, "Entered Blcny1 from Priso1/Priso2 (changes teleport from clouds at top of screen)", false},
{0x2B0, 7, "Entered Blcny1 from Prefa1/Prefa2 (changes teleport from clouds at top of screen)", false},
{0x2B1, 0, "Entered Blcny1 from Ring1 (changes teleport from clouds at top of screen)", false},
{0x2B8, 2, "[not sure how this is set - Misery not in Ring1]", false},
{0x2BA, 6, "Defeated Doctor (Mimiga dialogues change)", false},
{0x2BA, 7, "Started fighting Doctor   (note: not currently fighting, since it never gets unset)", false},
{0x2BB, 0, "Talked to Chaco once after defeating Doctor", false},
{0x2BB, 1, "[mimigas gone from Ring2? set after island starts to collapse]", false},
{0x2BB, 2, "Hearts appeared in Ring2 (talk to Chaco twice defeating Doctor)", false},
{0x2BD, 2, "Talked to Cthulhu in Cthu once", false},
{0x2C1, 0, "ITEM - Clay Figure Medal (after defeating Red Demon)", false},
{0x2C3, 4, "[something with Undead Core fight]", false},
{0x2C3, 5, "[island is collapsing - makes screen shake?]", false},
{0x2C7, 2, "Little Man is in Little", false},
{0x2C7, 3, "Can get Little Man (talked to Little Man's Wife)", false},
{0x2C7, 4, "Traded Blade for Nemesis", false},
{0x2C7, 5, "[UNUSED - never set, Little Man dialogue jump target doesn't exist - there's also an incomplete event in the script]", false},
{0x2C9, 6, "Helicopter in Blcny2", false},
{0x2C9, 7, "Sue in Blcny2 near Ring1 entrance", false},
{0x2CA, 0, "Sue in Blcny2 at cliff's edge", false},
{0x2CA, 1, "Opens door from Blcny2 to Prefa2", false},
{0x2D0, 0, "Curly on bed", false},
{0x2D0, 1, "Can drain Curly (after reading notebook)", false},
{0x2D0, 2, "Curly drained", false},
{0x2D0, 3, "Can take Curly from bed (after reboot time message)", false},
{0x2D0, 4, "Currently have Curly (drained) on your back", false},
{0x2D0, 5, "Can read notebook (after using computer)", false},
{0x2D2, 4, "[set when carried by Balrog, but has no effect?]", false},
{0x2DB, 2, "POWER-UP - Life Capsule in Hell1", false},
{0x2DB, 3, "Curly is in Hell1", false},
{0x2DB, 4, "Currently have Curly (not shooting) on your back", false},
{0x2DB, 5, "Currently have Curly (shooting) on your back", false},
{0x2DB, 6, "[enables Hell enemies etc.?  set when entering Hell1 from Prefa2, so there's no avoiding it]", false},
{0x2DD, 6, "[changes something when entering Hell3 from Hell2?  set when entering Hell1, cleared after defeating Heavy Press?]", false},
{0x2DD, 7, "POWER-UP - Missiles in Hell3 (note: if you get the Missile Launcher here, it has 100 ammo)", false},
{0x2DF, 0, "[Ma Pignon not in Mapi - how is this set?]", false},
{0x2DF, 1, "Mentioned amnesia to Ma Pignon", false},
{0x2DF, 2, "ITEM - Mushroom Badge", false},
{0x2DF, 3, "Viewed Mushroom Badge description on menu (so you know it's worthless)", false},
{0x2DF, 4, "Currently fighting Ma Pignon (locks door from Mapi to Cemet)", false},
{0x2E2, 6, "Shot Statue 1", false},
{0x2E2, 7, "Shot Statue 2", false},
{0x2E3, 0, "Shot Statue 3", false},
{0x2E3, 1, "Shot Statue 4", false},
{0x2E4, 0, "Fought Ballos Head once (must kill it twice to finally defeat him)", false},
{0x2E6, 4, "Ballos's dog not in Ostep", false},
{0x2E9, 0, "ITEM - Polar Star", false},
{0x2E9, 1, "Hermit Gunsmith not asleep in Pole", false},
{0x2E9, 2, "Signpost in Pole", false},
{0x2E9, 3, "Hermit Gunsmith awake in Pole", false},
{0x2E9, 4, "ITEM - Spur", false},
{0x2F0, 4, "ITEM - Nikumaru Counter", false},
{0x316, 0, "Got best ending (set when carried by Balrog)", false},
{0x393, 0, "Current Puppy is Hajime", false},
{0x393, 1, "Current Puppy is Mick", false},
{0x393, 2, "Current Puppy is Shinobu", false},
{0x393, 3, "Current Puppy is Kakeru", false},
{0x393, 4, "Current Puppy is Nene", false},
{0x410, 0, "[rising water? set after defeating core, cleared after drowning cutscene]", false},
// clang-format on

#endif
